version: '3.8'

services:
  avito_testcase:
    build: ./
    command: ./wait-for-postgres.sh db ./avito_testcase
    volumes:
      - ./logs:/app/logs
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    environment:
      - DB_PASSWORD=admin
      - REDIS_PASSWORD=admin


  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./database/postgres/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - 5415:5432
  
  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./databaseRedis/data:/data
    environment:
      - REDIS_PASSWORD=admin
    ports:
      - 6310:6379
